### ISSUE TITLE
ProjectFunctionCpu Not Working

### ISSUE THREAD

**Issue by rlukata** [pulumiverse/pulumi-vercel#235]
Did ProjectFunctionCpu become deprecated? Out of nowhere it begun returning the following error:
`[unexpected error: not_found - Not Found](error: Error updating project Function CPU: Could not update function CPU, unexpected error: not_found - Not Found)`.

**Comment by omercnet** [comment]
see deprecation notice
https://github.com/vercel/terraform-provider-vercel/blob/71a655f75a51b204e511a76b2f7419fca99e2789/docs/data-sources/project_function_cpu.md#vercel_project_function_cpu-data-source
