### ISSUE TITLE
🐛 can't refresh the stack if an EnvironmentVariable is removed

### ISSUE THREAD

**Issue by LouisAmon** [pulumiverse/pulumi-vercel#63]
Hi,

I've provisioned an envvar via `pulumi-vercel`, then I removed it manually via the Vercel console

When I `pulumi refresh`, I get this error:
```
error: Preview failed: Expected an Object, got: {<nil>}
```

**Comment by omercnet** [comment]
I've noticed this as well - it's an issue with the upstream provider I'll try and fix it there
