### ISSUE TITLE
Add "team" setting to "Install & Config" documentation

### ISSUE THREAD

**Issue by lenardchristopher** [pulumiverse/pulumi-vercel#80]
There are two config settings - `apiToken` and `team`, but only `apiToken` is in the documentation. I had to go into the code to find `team` and think it would be best if it was explained in the documentation instead.

Thanks for putting this provider together. Very happy to have it.

**Comment by omercnet** [comment]
Great point, thanks for the suggestion 
Mind opening a PR with the fix to the readme and docs ?
